- name: "services"
  label: "Usługi"
  files:
    - name: "services"
      label: "Lista Usług"
      file: "src/data/services.json"
      fields:
        - { label: "Tytuł", name: "title", widget: "string" }
        - { label: "Podtytuł", name: "subtitle", widget: "text" }
        - label: "Usługi"
          name: "services"
          widget: "list"
          fields:
            - { label: "Nazwa", name: "name", widget: "string" }
            - { label: "Opis", name: "description", widget: "text" }
            - { label: "Cena", name: "price", widget: "string" }
            - { label: "Obraz", name: "image", widget: "image" }
            - { label: "Wyróżniona", name: "featured", widget: "boolean", default: false }
            - label: "Cechy"
              name: "features"
              widget: "list"
              field: { label: "Cecha", name: "feature", widget: "string" }
        - label: "Wezwanie do Działania"
          name: "cta"
          widget: "object"
          fields:
            - { label: "Tytuł", name: "title", widget: "string" }
            - { label: "Opis", name: "description", widget: "text" }
            - { label: "Tekst Przycisku", name: "button_text", widget: "string" }