backend:
  name: git-gateway
  branch: main

locale: 'pl'

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://karolinagfotografia.pl
display_url: https://karolinagfotografia.pl

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "site_content"
    label: "Treść Strony"
    files:
      - label: "Strona Główna - Hero"
        name: "hero"
        file: "src/data/hero.json"
        fields:
          - {label: "Tytuł", name: "title", widget: "string"}
          - {label: "Opis", name: "description", widget: "text"}
          - {label: "Obraz", name: "image", widget: "image"}
      
      - label: "O mnie"
        name: "about"
        file: "src/data/about.json"
        fields:
          - {label: "Tytuł", name: "title", widget: "string"}
          - {label: "Opis", name: "description", widget: "text"}
          - {label: "Obraz", name: "image", widget: "image"}
      
      - label: "Kontakt"
        name: "contact"
        file: "src/data/contact.json"
        fields:
          - {label: "Tytuł", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefon", name: "phone", widget: "string"}
      
      - label: "Konfiguracja Strony"
        name: "site"
        file: "src/data/site.json"
        fields:
          - {label: "Tytuł strony", name: "title", widget: "string"}
          - {label: "Opis", name: "description", widget: "text"}
          - {label: "Email", name: "email", widget: "string"}